name: ci-cd

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    name: CI - Test & Build
    runs-on: ubuntu-latest

    steps:
      # 1) Check out source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Set up Node (adjust version for your stack)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3) Install dependencies
      - name: Install deps
        run: npm ci

      # 4) Run tests
      - name: Test
        run: npm test

      # 5) Build (compilation/bundling if applicable)
      - name: Build
        run: npm run build

  cd:
    name: CD - Docker Build & Push (main only)
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      # 1) Check out source code again for this job
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Set up Docker Buildx (better caching/multi-platform)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Log in to Docker Hub (use GitHub Secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) Compute tags (latest + short SHA)
      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/ci-cd-test
          tags: |
            # publish latest only on default branch (usually main)
            type=raw,value=latest,enable={{is_default_branch}}
            # commit SHA tags for precise rollbacks
            type=sha,format=long
            type=sha,format=short,prefix=

      # 5) Build and push the image
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # optional build cache:
          cache-from: type=gha
          cache-to: type=gha,mode=max
